name: Water Wahine Fitness
favicon: null
layout_spectrum: 0.5053763
typography_spectrum: 0.3028674
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Lauren Murata, Fitness Instructor '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9bd0ff'
    - '#ffffff'
    - '#163d8c'
    - '#457cd8'
  brandStrength: 0.1366230701096356
  lightness: 0.3432760408613831
  saturation: 0.4594730907119811
  rhythmicContrast: 0.03955298056825995
purpose: []
