title: 'Lauren Murata, Fitness Instructor '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4594730907119811
  brandStrength: 0.1366230701096356
  rhythmicContrast: 0.03955298056825995
  brandColors:
    - '#000000'
    - '#9bd0ff'
    - '#ffffff'
    - '#163d8c'
    - '#457cd8'
  lightness: 0.3432760408613831
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Water Wahine Fitness
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3028674
layout_spectrum: 0.7473118
